project:
  type: website

website:
  title: "ISSS626: GAA"
  navbar:
    left:
      - text: Hands-on Exercise
        menu: 
          - text: "1a: Geospatial Data Wrangling with R"
            href: Hands-on Exercise/Hands-on_Ex01a/Hands-on_Ex01a.qmd
          - text: "1b: Choropleth Mapping with R"
            href: Hands-on Exercise/Hands-on_Ex01b/Hands-on_Ex01b.qmd
          - text: "Hands-on Exercise 2"
            href: Hands-on Exercise/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: "Hands-on Exercise 3"
            href: Hands-on Exercise/Hands-on_Ex03/Hands-on_Ex03.qmd
          - text: "Hands-on Exercise 4"
            href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex04.qmd
          - text: "Hands-on Exercise 5"
            href: Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex05.qmd
          - text: "Hands-on Exercise 6"
            href: Hands-on Exercise/Hands-on_Ex06/Hands-on_Ex06.qmd
          - text: "Hands-on Exercise 7"
            href: Hands-on Exercise/Hands-on_Ex07/Hands-on_Ex07.qmd
          - text: "Hands-on Exercise 8"
            href: Hands-on Exercise/Hands-on_Ex08/Hands-on_Ex08.qmd
          - text: "Hands-on Exercise 9"
            href: Hands-on Exercise/Hands-on_Ex09/Hands-on_Ex09.qmd
          - text: "Hands-on Exercise 10"
            href: Hands-on Exercise/Hands-on_Ex10/Hands-on_Ex10.qmd
      - text: In-class Exercise
        menu: 
          - text: "In-class Exercise 1"
            href: In-class Exercise/In-class_Ex01/In-class_Ex01.qmd
          - text: "In-class Exercise 2"
            href: In-class Exercise/In-class_Ex02/In-class_Ex02.qmd
          - text: "In-class Exercise 3"
            href: In-class Exercise/In-class_Ex03/In-class_Ex03.qmd
          - text: "In-class Exercise 4"
            href: In-class Exercise/In-class_Ex04/In-class_Ex04.qmd
          - text: "In-class Exercise 5"
            href: In-class Exercise/In-class_Ex05/In-class_Ex05.qmd
          - text: "In-class Exercise 6"
            href: In-class Exercise/In-class_Ex06/In-class_Ex06.qmd
          - text: "In-class Exercise 7"
            href: In-class Exercise/In-class_Ex07/In-class_Ex07.qmd
          - text: "In-class Exercise 8"
            href: In-class Exercise/In-class_Ex08/In-class_Ex08.qmd
          - text: "In-class Exercise 9"
            href: In-class Exercise/In-class_Ex09/In-class_Ex09.qmd
          - text: "In-class Exercise 10"
            href: In-class Exercise/In-class_Ex10/In-class_Ex10.qmd
      - text: Take-home Exercise
        menu: 
          - text: "Take-home Exercise 1"
            href: Take-home Exercise/Take-home_Ex01/Take-home_Ex01.qmd
          - text: "Take-home Exercise 2"
            href: Take-home Exercise/Take-home_Ex02/Take-home_Ex02.qmd
          - text: "Take-home Exercise 3"
            href: Take-home Exercise/Take-home_Ex03/Take-home_Ex03.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/rydia-liang/"      
format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual
